# logging options
save_dir: /mnt/WZN/HistoBistro-main/test_data/output
project: shiguanaitest
name: debug

# task definition
data_config: /mnt/WZN/HistoBistro-main/test_data/data_config.yaml
task: binary
target: cancer
num_classes: 1
cohorts: [shiguanai]
ext_cohorts: []
clini_info: {}
seed: null
label_dict:
  negative: 0
  positive: 1

# model options
model: Transformer
model_config:
  heads: 8
  dim_head: 64
  dim: 512
  mlp_dim: 512
norm: raw
feats: retccl
input_dim: 768
num_tiles: -1
pad_tiles: false

# training options
folds: 4
num_epochs: 5
criterion: BCEWithLogitsLoss
optimizer: AdamW
lr_scheduler: null
lr_scheduler_config: null
lr: 2.0e-05
wd: 2.0e-05
bs: 1
stop_criterion: loss
val_check_interval: 500
num_samples: null
